language: node_js
sudo: required
node_js:
  - stable
branches:
  only:
  - travis-ci
install:
  - travis_retry npm install
script:
  - npm test
  - npm run cover
after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"
